### PR TITLE
ensure cellfinder-core can run on single cpu

### LINKED ISSUE #197: Cellfinder core should run on just one cpu
See https://github.com/brainglobe/cellfinder-napari/issues/157#issuecomment-1634074975

### PR DESCRIPTION
**Pull request by alessandrofelder**
## Description

**What is this PR**

- [x] Bug fix
- [ ] Addition of a new feature
- [ ] Other

**Why is this PR needed?**
It's currently possible for cellfinder-core to spawn a threadpool with 0 processes.
See https://github.com/brainglobe/cellfinder-napari/issues/157

**What does this PR do?**
Ensures `n_ball_procs` is always at least 1, and therefore a thread pool with 0 processes is never spawned.

## References

Closes #197 and _should_ get us most of the way to https://github.com/brainglobe/cellfinder-napari/issues/157

## How has this PR been tested?
Added a test parameter to check this edge case

## Is this a breaking change?

No

## Checklist:

- [x] The code has been tested locally
- [x] Tests have been added to cover all new functionality (unit & integration)
- [x] The documentation has been updated to reflect any changes
- [x] The code has been formatted with [pre-commit](https://pre-commit.com/)

### CODE REVIEW

**Comment by alessandrofelder** [comment]
Still need to test this on a real-life dataset (first thing tomorrow) - will confirm here.

**Comment by adamltyson** [comment]
Should we add tests for `cellfinder-napari` in the same way we do for `cellfinder`? Or just wait until we merge `cellfinder-core` & `cellfinder-napari`?

**Comment by alessandrofelder** [comment]
> Should we add tests for `cellfinder-napari` in the same way we do for `cellfinder`? Or just wait until we merge `cellfinder-core` & `cellfinder-napari`?

I think it's not much work to add the additional tests to this workflow, and takes pressure off the merging repo timeline, so a good idea? Opened #201

**Review by adamltyson — APPROVED** [review]

**Comment by alessandrofelder** [comment]
Confirming this ran on real-life large test data on 1 CPU and gave the same result as with 17 CPUs (took ~2:15 h instead of 1:05 h)

**Pull request merged**
