### PR TITLE
Add cellfinder tests to CI

### PR DESCRIPTION
**Pull request by dstansby**
Fixes https://github.com/brainglobe/cellfinder-core/issues/59. The added test intentionally fails - and will be fixed by https://github.com/brainglobe/cellfinder-core/pull/58.

### CODE REVIEW

**Comment by dstansby** [comment]
Current status is the new tests I've added should fail (and then be fixed by https://github.com/brainglobe/cellfinder-core/pull/58). They fail if this PR includes the changes in https://github.com/brainglobe/cellfinder-core/pull/62 to enable `setuptools_scm` versioning, but do not fail otherwise.

I have no idea why this is 🤷 , or why it should be, and it's too hot now so I'm clocking off for the weekend, but hopefully can debug a bit further next week...

**Review by paddyroddy — CHANGES_REQUESTED** [review]
Looks fine, but I really feel that this should be a separate workflow, i.e. in its own file

**Comment by dstansby** [comment]
> Looks fine, but I really feel that this should be a separate workflow, i.e. in its own file

Why? I could make this into a re-usable action (but not sure it's worth it?), but having it in the same workflow allows it to depend on the linting job.

**Comment by paddyroddy** [comment]
> Why? I could make this into a re-usable action (but not sure it's worth it?), but having it in the same workflow allows it to depend on the linting job.

Picture the scenario in which you are a new contributor to an existing code base that you aren't really familiar with. The workflow fails, and then you have to go down the rabbit hole to work out where exactly it failed within a given workflow file.

If you look at other projects, e.g. [pandas](https://github.com/pandas-dev/pandas/tree/main/.github/workflows), it is common practice to have multiple workflow files and a given run only "passes" if all workflow files run. At first glance (assuming the workflow is given a sensible name) it is trivial to see what succeeded and what didn't.

Let's say that you have one workflow files with three steps: `A`, `B` and `C`. The workflow passes for `A`, and then fails for `B`. You then fix `B` and then `C` fails. You then fix `C` and good-to-go. One could avoid this by having separate workflow files (or non-sequential jobs - but then less obvious at first glance), let's say one for `A`, `B` and `C`. You run first time and find that `B` and `C` fail. You then fix both at the same time and good-to-go. 

For reference, my thought process still holds from an earlier discussion on whether linting should be a different file or not. IMO, if a process is so lightweight like linting, then there is absolutely no harm in it being standalone. I agree it is different for a heavy-duty job

**Comment by adamltyson** [comment]
I'm not sure I see an obvious benefit from one way or another. As far as I can tell, if you have seperate files, then the individual steps are split up on the main Actions tab, but if they're in the same file, they're split up within a specific workflow. I don't see that one is necessarily easier to understand than the other.

**Comment by dstansby** [comment]
I've updated this so the tests don't depend on the linting job, and so the packaging also depends on the new `cellfinder` tests. @paddyroddy if you think these should be split into different files, then I think that's a discussion for another issue or PR - we're currently taking the single workflow approach across brainglobe projects we're working on.

**Review by paddyroddy — APPROVED** [review]

**Pull request merged**
