### PR TITLE
fixing loading from txt file with dask

### PR DESCRIPTION
**Pull request by npeschke**
Hi I ran into the issue that loading images from a text file is not possible anymore with dask (https://github.com/brainglobe/cellfinder/issues/184)

This is intended as a temporary fix for this bug until a better solution with imio comes.

### CODE REVIEW

**Comment by adamltyson** [comment]
Hi @npeschke, thanks for this!

Would you mind adding a test? Just something small to check that a dask array is being generated with this logic? There's test data in this repo that could be used.

**Comment by npeschke** [comment]
I added a basic type check for the loading from a txt and an equality check of stack comparing both ways of creating it.
The test takes about a second to run on my machine so I am unsure if it should be marked slow.

**Comment by adamltyson** [comment]
Looks great, thanks again!

Eventually all of this I/O and dask support should move to imio, so we can support more data formats with dask, across all software. This general issue has been moved to https://github.com/brainglobe/imio/issues/5, if you feel like tackling some more issues @npeschke!

**Comment by adamltyson** [comment]
@npeschke  is there a need for this to be on PyPI soon, or can it wait for the next release?

**Comment by npeschke** [comment]
It would be nice to have that in PyPI soon, I plan to deploy cellfinder on a HPC cluster and this would make life easier for the admins that install cellfinder. Thanks for asking!

**Comment by adamltyson** [comment]
No worries, I'll aim to have it out by the end of the day. 

What kind of cluster is it? If you're using SLURM, I can probably help. If not, would you be willing to (very briefly) document the process, to put in the [docs](https://docs.brainglobe.info/cellfinder/installation/cluster-installation) and help out others?

**Comment by adamltyson** [comment]
`cellfinder-core==0.2.8` is out now.

**Comment by npeschke** [comment]
Thank you very much for the new build! Indeed I use as SLURM cluster and I am planning to wrap it into a snakemake workflow.

**Pull request merged**
