### PR TITLE
Add cython language level for tox

### LINKED ISSUE #61: [BUG] Cython language_level warning
When testing with `tox`, the following warning is raised:

```python
/Users/dstansby/projects/napari/cellfinder-core/.tox/.package/lib/python3.9/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/dstansby/projects/napari/cellfinder-core/src/cellfinder_core/detect/filters/plane/base_tile_filter.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
```
The important bit is
> Cython directive 'language_level' not set, using 2 for now (Py2).

I'm not sure whether this should be set to 2 or 3, but either way this should be manually set to avoid issues due to the default value potentially changing in future versions of Cython.

### PR DESCRIPTION
**Pull request by paddyroddy**
Fixes #61. `tox` should also be included as a dev requirement (and order alphabetically)

### CODE REVIEW

**Review by dstansby — COMMENTED** [review]
Looks good - from memory there are other `.pyx` files elsewhere in the repo, so it's probably worth checking they have the language level set too?

**Comment by paddyroddy** [comment]
> Looks good - from memory there are other `.pyx` files elsewhere in the repo, so it's probably worth checking they have the language level set too?

Didn't change because no warning, but yes there is no harm. Will do that now and merge

**Comment by dstansby** [comment]
@paddyroddy I didn't approve this PR, and the tests haven't finished running, so I don't think this should have been merged! It looks like you've added comments to `.py` files that aren't needed, so could you open a new PR to revert those changes?

**Comment by paddyroddy** [comment]
This is precisely why I dislike the way to do PRs for napari...

**Comment by dstansby** [comment]
Regardless of what the convention of who merges PRs is, there should still be an approval by a dev who isn't the PR author before someone merges.

**Comment by dstansby** [comment]
And the tests should run and be passing before merging too

**Comment by paddyroddy** [comment]
> Regardless of what the convention of who merges PRs is, there should still be an approval by a dev who isn't the PR author before someone merges.

You mean like this 😉  https://github.com/brainglobe/cellfinder-core/pull/54

**Comment by paddyroddy** [comment]
> And the tests should run and be passing before merging too

This can be enforced at the repo setting level, which I think we should @adamltyson

**Comment by adamltyson** [comment]
>This can be enforced at the repo setting level, which I think we should @adamltyson

I'll think about it, previously it wasn't an issue as fewer people had the rights to merge.

>This is precisely why I dislike the way we do PRs for napari...

Curious to know what you dislike?

**Comment by paddyroddy** [comment]
> Curious to know what you dislike?

Due to this (perceived) pressure for faster reviews, I'm more inclined to make mistakes/faux pas than the model I'm used to of:
* Author A creates PR
* Reviewer B/C/ etc reviews PR
* Author A merges PR

**Comment by adamltyson** [comment]
> 
    Author A creates PR
    Reviewer B/C/ etc reviews PR
    Author A merges PR

Is this not how it's been working?

**Comment by paddyroddy** [comment]
> Is this not how it's been working?

No we (I) have been encouraged to merge as a reviewer if no comments

**Comment by adamltyson** [comment]
Ah yes. I think the aim of that workflow is to speed up merges, but only by reducing the number of steps, not by adding any pressure to review or merge any quicker.

**Comment by paddyroddy** [comment]
> Ah yes. I think the aim of that workflow is to speed up merges, but only by reducing the number of steps, not by adding any pressure to review or merge any quicker.

This may well only affect me, but I've never felt "rushed" using the other model

**Comment by dstansby** [comment]
Why do you feel rushed using this model? Perhaps it's wanting to open a PR before it's ready to be merged? In that case the trick is to open it as a draft PR, and then take it out of draft status and request a reviewer when it's ready to be reviewed/merged.

**Comment by paddyroddy** [comment]
> Why do you feel rushed using this model? Perhaps it's wanting to open a PR before it's ready to be merged? In that case the trick is to open it as a draft PR, and then take it out of draft status and request a reviewer when it's ready to be reviewed/merged.

No, it's not that. It's the very nature of it being merged beyond my control. You always think of extra things between creating a PR (draft or actual) and it being merged. It's out my control

**Pull request merged**
